# ä½ç½®æƒ…å ±ã®ã¿ã‚’å®šç¾©ã™ã‚‹ YAML
# suimon.yaml / targets.yaml ã‚’å‚è€ƒã«ã€æ°´é–€ã¾ã‚ã‚Šã®5åœ°ç‚¹ã‚’ã¾ã¨ã‚ã¦ã„ã¾ã™ã€‚
locations:
  - id: suimon-1
    name: "æ°´é–€ #1"
    latitude: 39.80219519075745
    longitude: 141.13317980590008
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-2
    name: "æ°´é–€ #2"
    latitude: 39.80314253510342
    longitude: 141.13606258796432
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-3
    name: "æ°´é–€ #3"
    latitude: 39.802007370732724
    longitude: 141.1355385713421
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-4
    name: "æ°´é–€ #4"
    latitude: 39.80279443153987
    longitude: 141.13434547274002
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-5
    name: "æ°´é–€ #5"
    latitude: 39.80336650658442
    longitude: 141.13296978414344
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-6
    name: "æ°´é–€ #6"
    latitude: 39.29844365684667
    longitude: 141.12411389547805
    icon: "ğŸŒŠ"
    color: "#4e9bff"

  - id: suimon-7
    name: "æ°´é–€ #7"
    latitude: 39.299216494142705
    longitude: 141.12382711660644
    icon: "ğŸŒŠ"
    color: "#4e9bff"